name: Cron 5min Check

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "hello world"
          date -u
